version: '3.8'

services:
  backend:
      build:
        context: .
        dockerfile: OrderManagement.API/Dockerfile
      ports:
        - "5000:80"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - MongoDB__ConnectionString=mongodb://mongo:27017
        - SqlServer__ConnectionString=Server=sqlserver;Database=OrderDb;User Id=sa;Password=Password1234;Encrypt=True;TrustServerCertificate=True;
      depends_on:
        - mongodb
        - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      SA_PASSWORD: "Password1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017

volumes:
  sql_data:
  mongo_data:
