// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagement.Infrastructure.Data;

#nullable disable

namespace OrderManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagement.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("beb70355-350d-4c03-b3dd-608c2d7c6ecb"),
                            Email = "john.doe@example.com",
                            Name = "John Doe",
                            Phone = "123-456-7890"
                        });
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5475b04-4b6a-4f0f-ab6d-ae3a274ff9fc"),
                            CustomerId = new Guid("beb70355-350d-4c03-b3dd-608c2d7c6ecb"),
                            OrderDate = new DateTime(2025, 2, 7, 15, 38, 23, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TotalAmount = 24.00m
                        },
                        new
                        {
                            Id = new Guid("109909ef-a52c-4aa7-a9f5-9cd0df8f48e7"),
                            CustomerId = new Guid("beb70355-350d-4c03-b3dd-608c2d7c6ecb"),
                            OrderDate = new DateTime(2025, 2, 7, 15, 38, 23, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalAmount = 26.00m
                        },
                        new
                        {
                            Id = new Guid("1cb90969-73e3-4d34-94a2-48acc8300062"),
                            CustomerId = new Guid("beb70355-350d-4c03-b3dd-608c2d7c6ecb"),
                            OrderDate = new DateTime(2025, 2, 7, 15, 38, 23, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            TotalAmount = 80.00m
                        });
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalPrice");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11b23121-17ed-4b15-9dd2-2a9dc3cc288c"),
                            OrderId = new Guid("e5475b04-4b6a-4f0f-ab6d-ae3a274ff9fc"),
                            ProductId = new Guid("19bb2513-fedf-44b6-c44c-08dd43d9cd34"),
                            ProductName = "Calabresa",
                            Quantity = 1,
                            TotalPrice = 24.00m,
                            UnitPrice = 24.00m
                        },
                        new
                        {
                            Id = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            OrderId = new Guid("109909ef-a52c-4aa7-a9f5-9cd0df8f48e7"),
                            ProductId = new Guid("1a44f41f-b7d2-41c9-9497-0bc2c1a2613b"),
                            ProductName = "Marguerita",
                            Quantity = 1,
                            TotalPrice = 26.00m,
                            UnitPrice = 26.00m
                        },
                        new
                        {
                            Id = new Guid("d3158cfc-72e9-43a7-9b5e-34e2d9a55f61"),
                            OrderId = new Guid("1cb90969-73e3-4d34-94a2-48acc8300062"),
                            ProductId = new Guid("f04acbb2-9c97-4fae-853b-e1c1e52715a2"),
                            ProductName = "Quatro queijos",
                            Quantity = 2,
                            TotalPrice = 80.00m,
                            UnitPrice = 40.00m
                        });
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19bb2513-fedf-44b6-c44c-08dd43d9cd34"),
                            Name = "Calabresa",
                            Price = 24.00m
                        },
                        new
                        {
                            Id = new Guid("1a44f41f-b7d2-41c9-9497-0bc2c1a2613b"),
                            Name = "Marguerita",
                            Price = 26.00m
                        },
                        new
                        {
                            Id = new Guid("f04acbb2-9c97-4fae-853b-e1c1e52715a2"),
                            Name = "Quatro queijos",
                            Price = 40.00m
                        });
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
